syntax = "proto3";

package order;

option go_package = "ifpb.com/microservices-proto/golang/order";

message OrderItem {
  string product_id = 1;
  int32 quantity = 2;
  double unit_price = 3;
}

message CreateOrderRequest {
  string customer_id = 1;
  repeated OrderItem items = 2;
}

message CreateOrderResponse {
  string order_id = 1;
  string customer_id = 2;
  double total_amount = 3;
  string status = 4;
  int32 delivery_days = 5;
  repeated OrderItem items = 6;
}

service OrderService {
  rpc CreateOrder(CreateOrderRequest) returns (CreateOrderResponse);
}